#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
#


AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 20
    MemorySize: 256

Resources:
  ETLFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
         Variables:
           S3Bucket: '*'
           LogLevel: INFO
      Policies:
        - S3WritePolicy: 
            BucketName: '*'
      Events:
        UpdateEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 /15 * * ? *)

  Bucket:
    Type: AWS::S3::Bucket

Outputs:
  ETLFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt ETLFunction.Arn
